services:
  # Flask Backend API
  - type: web
    name: clinical-trials-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT api.index:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: ./api
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
    healthCheckPath: /api/health
    
  # Next.js Frontend
  - type: web
    name: clinical-trials-frontend
    env: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: clinical-trials-api
          property: host
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false